### ISSUE TITLE
arbitrary <br> tag generated by {{#each}} loop

### ISSUE THREAD

**Issue by SGillessen** [CalderaWP/caldera-metaplate#16]
![screenclip](https://cloud.githubusercontent.com/assets/10210934/6203554/9a30baf8-b527-11e4-9215-8a1f79e897c7.png)
![screenclip](https://cloud.githubusercontent.com/assets/10210934/6203557/9fd55d1a-b527-11e4-8a56-79518b86a054.png)

arbitrary <br> tag generated by {{#each}} loop

**Comment by Shelob9** [comment]
@SGillessen Good catch.

@Desertsnowman I assume this is because we put the output through the_content filter. That's because we need texturize/autop on the content and to do shortcodes. But it's also going to texturize/autop the template itself, which is not what one should expect would happen or makes sense.

Can we texturize/autop post content if used and do_shortcode the rest?

**Comment by Desertsnowman** [comment]
He can be taught!
That's exactly the reason. I'll make an patch to correct it.

-------- Original message --------

**Comment by SGillessen** [comment]
@Desertsnowman Who can be taught on what? Hope you don't mean me ;)

**Comment by Desertsnowman** [comment]
@SGillessen I was talking to @Shelob9 . we had a similar thing with a form script not loading.
But I know the problem here and will be sorting it soon.
